### PR TITLE
feat: provide example themes

### PR DESCRIPTION
**Pull request by Nerixyz**
Related to #32

### CODE REVIEW

**Comment by Ic3Nine** [comment]
Thank you for this.  I've tried all three samples you provided by creating a default theme.css but I'm still only getting the default green background.  I've tried full refresh with ctrl +f5 and restarting the app.

**Comment by Nerixyz** [comment]
It should work with the [latest alpha release](https://github.com/Nerixyz/current-song2/releases):

```
SomeFolder
|
+-- current-song2.exe
+-- config.toml
+-- theme.css
```

I made some updates, maybe your version had some bugs, try the new version.

**Comment by Ic3Nine** [comment]
New version works great in Win10.  However, it does not work in Win11 at all.  No song display shows up.  Theme, no theme, exclude include... tried all.

**Comment by Nerixyz** [comment]
> However, it does not work in Win11 at all.

Did you try spotify? I'd expect at least Spotify to work. You should be able to turn on debug logging by setting `RUST_LOG=debug` in the environment variables.

**Pull request merged**
